version: 2.1
orbs:
  node: circleci/node@5.0.0
  aws-cli: circleci/aws-cli@2.1.0
  eb: circleci/aws-elastic-beanstalk@2.0.1
jobs:
  build:
    docker:
      - image: "cimg/base:stable"
    executor: node/default
    steps:
      - node/install
      - checkout
      - run:
          name: Front-End Install
          command: |
            npm run install:frontend
      - run:
          name: Front-End Build
          command: |
            npm run build:frontend
      - run:
          name: Front-End test
          command: |
            npm run test:frontend
      - run:
          name: Back-End Install
          command: |
            npm run install:backend
      - run:
          name: Back-End Build
          command: |
            npm run build:backend
