version: 2.1
orbs:
  node: circleci/node@4.7.0
  eb: circleci/aws-elastic-beanstalk@2.0.1
  aws-cli: circleci/aws-cli@2.0.3
jobs:
  build:
    docker:
      - image: "cimg/base:stable"
    steps:
      - node/install:
          node-version: '16.13'
      - checkout
      - aws-cli/setup
      - eb/setup
      - run:
          name: Front-End Install
          command: |
            npm run install:frontend
      - run:
          name: Back-End Install
          command: |
            npm run install:backend
      - run:
          name: Front-End Build
          command: |
            npm run build:frontend
      - run:
          name: Back-End Build
          command: |
            npm run build:backend
      - run:
          name: Back-End Deploy
          command: npm run deploy:backend
      - run:
          name: Front-End Deploy
          command: npm run deploy:frontend
          